## Intro to Python Programming
- Prof Joanna Bieri
- Office: Duke 209


### Day 14 - Functions

#### Basic Function Format

     def function_name(parameter1, parameter2,...):
         ''' Comments about the function '''
         code
         code
         code
         
         return value
         
#### Let's define a basic function named hello_world

all it will do is print the string Hello, world!

In [1]:
# Hello world function
def hello_world():
    '''Prints hello world.'''
    print('Hello, world!')

Notice that when we run the cell above, nothing happens. What this code is doing is creating your function and storing it in Python's memory. So then at any time later you can use it.

In [2]:
hello_world()

Hello, world!

Notice that when you call the function... then you get the output. And we could call the function as many times as we want!

In [3]:
for i in range(10):
    hello_world()

Hello, world!
Hello, world!
Hello, world!
Hello, world!
Hello, world!
Hello, world!
Hello, world!
Hello, world!
Hello, world!
Hello, world!

#### Functions autmoate things that we might want to do a lot.

In [4]:
# Here is some code that will take a first and last name and make a Redlands email.
first = 'Joanna'
last = 'Bieri'

email = f'{first.lower()}_{last.lower()}@redlands.edu'
print(email)

joanna_bieri@redlands.edu

If we put this code inside a function then we can always use it later. 

#### Lets create the function make_email

- it will contain two paramters: first and last
- it will use those parameters to build the email.
- it will print the email

To call the function we use make_email(first,last) sening it two arguments.

In [5]:
def make_email(first,last):
    '''Creates an email address for first last'''
    my_email = f'{first.lower()}_{last.lower()}@redlands.edu'
    print(my_email)

In [6]:
make_email('Joanna','Bieri')

joanna_bieri@redlands.edu

Notice that if we try to look at the variable my_email it does not exist!

In [7]:
my_email

NameError: name 'my_email' is not defined

This is because variables defined inside a function are deleted as soon as the function is done operating.

### Practice 1

#### Part 1
Write a function that takes two paramters a first name and a last name and then prints a message to that person.

eg. first = 'Joanna', last='bieri' then it should print "Hello Joanna Bieri!" notice that it should accept an all lower case name and change it to caplitalized.

Call your function with arguments matching your first and last name.

#### Part 2

Write a function that takes two paranters (both numbers) and prints the sum of those numbers.

In [8]:
# Write your function here
def make_message(first,last):
    '''Creates an message to first last name'''
    my_message = f'Good evening, {first} {last}!'
    print(my_message)

In [9]:
# Call your function here
make_message('Mazzie','Tetens')

Good evening, Mazzie Tetens!

In [10]:
# Write your function here
def sum_numbers(number1,number2):
    '''Sum of two numbers'''
    add_numbers = {number1 + number2}
    print(add_numbers)

In [11]:
# Call your function here
sum_numbers(9,91)

{100}

### Practice 2

Copy and paste your madlibs code from programming assignment 1. Turn this code into a function, that accepts the right number of paramters (on for each word you enter), and then prints out your story. See if you can improve the formatting of your story.

In [12]:
# Copy of your old code
# Mazzie Tetens
# Programming Assignment 1
# MadLibs

first_name = "Jack"
last_name = "Bear"
string1 = "banana"
integer1 = 1
float1 = 0.5
place1 = "kitchen"
place2 = "living room"
verb = "sleeping"

my_paragraph = f"My dog, {first_name} {last_name}, is an eating machine. One day in my house, I headed over to the "\
               f"{place1} to make a smoothie. Jack was {verb} all the way over in the {place2}. I open a {string1} "\
               f"and Jack looks at me. I go to put the {string1} in my smoothie cup and... I dropped it on the "\
               f"floor. {first_name.upper()}! after about {float1} seconds later, the {string1} is gone. I can't "\
               f"get mad at him because he is so cute, and it is okay, because I have {(integer1+1)} {string1}s."
print(my_paragraph)

My dog, Jack Bear, is an eating machine. One day in my house, I headed over to the kitchen to make a smoothie. Jack was sleeping all the way over in the living room. I open a banana and Jack looks at me. I go to put the banana in my smoothie cup and... I dropped it on the floor. JACK! after about 0.5 seconds later, the banana is gone. I can't get mad at him because he is so cute, and it is okay, because I have 2 bananas.

In [51]:
# Write your function here
# Write your function here
def madlibs(first_name, last_name, string1, integer1, float1, place1, place2, verb):
    '''Creates an message to first last name'''
    my_paragraph = (f"My dog, {first_name} {last_name}, is an eating machine. One day in my house, I headed over to the "\
                   f"{place1} to make a smoothie. Jack was {verb} all the way over in the {place2}. I open a {string1} "\
                   f"and Jack looks at me. I go to put the {string1} in my smoothie cup and... I dropped it on the "\
                   f"floor. {first_name.upper()}! after about {float1} seconds later, the {string1} is gone. I can't "\
                   f"get mad at him because he is so cute, and it is okay, because I have {(integer1+1)} {string1}s."
                   )
    print(my_paragraph)

In [52]:
# Enter the variables/arguments
first_name = "Jack"
last_name = "Bear"
string1 = "banana"
integer1 = 1
float1 = 0.5
place1 = "kitchen"
place2 = "living room"
verb = "sleeping"

# Call the function here
madlibs("Jack","Bear","banana",1,0.5,"kitchen","living room","sleeping")

My dog, Jack Bear, is an eating machine. One day in my house, I headed over to the kitchen to make a smoothie. Jack was sleeping all the way over in the living room. I open a banana and Jack looks at me. I go to put the banana in my smoothie cup and... I dropped it on the floor. JACK! after about 0.5 seconds later, the banana is gone. I can't get mad at him because he is so cute, and it is okay, because I have 2 bananas.

### Default Values and Optional Arguments.

Sometimes you want to have default values for different paramters into a function or arguments that are optional for the user to input.

We will start by creating a function. See if you can figure out what this does.

In [15]:
def write_email(first,last,product,date,number):
    '''Sends a message to first last
       product is something they have bought, default is cats
       date is the date of last purchase
       number is the number purchased'''
    if number >0:
        message = f'Dear {first.title()} {last.title()},'
        message += f'\nAs of {date} you have purchased {number} {product} from our company!\n'
        message += f'We thank you for your support.\n'
        message += f'Sincerely,\nManagement'
        print(message)
    else:
        message = f'Dear {first.title()} {last.title()},'
        message += f'\nSo far you have not purchased {product} from our company!\n'
        message += f'Sincerely,\nManagement'
        print(message)

### Practice 3

What does the function above do?

If I uncomment and run the command:

    write_email('Joanna','Bieri','cats','2-22-22',14)
   
what will it print?

In [53]:
# Your answer here:
write_email('Joanna','Bieri','cats','2-22-22',14)

TypeError: write_email() takes 2 positional arguments but 5 were given

#### Now let's let some of these parameters have default values:

Maybe my company really sells just one major product. And we notice that if we never purchased a product then we don't really need a date. Let's update the function.

In [54]:
def write_email(first,last,product='cats',date=False,number=0):
    '''Sends a message to first last
       product is something they have bought, default is cats
       date is the date of last purchase (optional)
       number is the number purchased (optional)'''
    if number >0:
        message = f'Dear {first.title()} {last.title()},'
        message += f'\nAs of {date} you have purchased {number} {product} from our company!\n'
        message += f'We thank you for your support.\n'
        message += f'Sincerely,\nManagement'
        print(message)
    else:
        message = f'Dear {first.title()} {last.title()},'
        message += f'\nSo far you have not purchased {product} from our company!\n'
        message += f'Sincerely,\nManagement'
        print(message)

In [55]:
# Now for someone new to our company we could call the function with
write_email('Joanna','Bieri')

Dear Joanna Bieri,
So far you have not purchased cats from our company!
Sincerely,
Management

In [56]:
# But we still have the option to change some things. Maybe we got a new product:
write_email('Joanna','Bieri',product='dogs')

Dear Joanna Bieri,
So far you have not purchased dogs from our company!
Sincerely,
Management

In [57]:
# Or maybe we still want to do the full thing
write_email('Joanna','Bieri',product='dogs',date='2-22-22',number=7)

Dear Joanna Bieri,
As of 2-22-22 you have purchased 7 dogs from our company!
We thank you for your support.
Sincerely,
Management

#### Next lets add an optional argument.

In [58]:
def write_email(first,last,product='cats',date=False,number=0,sale_date=''):
    '''Sends a message to first last
       product is something they have bought, default is cats
       date is the date of last purchase (optional)
       number is the number purchased (optional)
       if a sale_date is given the message also inclused information about the sale.'''
    
    if sale_date:
        if number >0:
            message = f'Dear {first.title()} {last.title()},'
            message += f'\nAs of {date} you have purchased {number} {product} from our company!\n'
            message += f'The {product} are on sale starting {sale_date}.\n'
            message += f'Sincerely,\nManagement'
            print(message)
        else:
            message = f'Dear {first.title()} {last.title()},'
            message += f'\nSo far you have not purchased {product} from our company!\n'
            message += f'The {product} are on sale starting {sale_date}.\n'
            message += f'Sincerely,\nManagement'
            print(message)
    else:
        if number >0:
            message = f'Dear {first.title()} {last.title()},'
            message += f'\nAs of {date} you have purchased {number} {product} from our company!\n'
            message += f'We thank you for your support.\n'
            message += f'Sincerely,\nManagement'
            print(message)
        else:
            message = f'Dear {first.title()} {last.title()},'
            message += f'\nSo far you have not purchased {product} from our company!\n'
            message += f'Sincerely,\nManagement'
            print(message)

In [59]:
# Now for someone new to our company:
write_email('Joanna','Bieri')
print('--------------------')
# Maybe we got a new product:
write_email('Joanna','Bieri',product='dogs')
print('--------------------')
# Now maybe we are having a sale!
write_email('Joanna','Bieri',product='dogs',sale_date='3-22-22')
print('--------------------')

Dear Joanna Bieri,
So far you have not purchased cats from our company!
Sincerely,
Management
--------------------
Dear Joanna Bieri,
So far you have not purchased dogs from our company!
Sincerely,
Management
--------------------
Dear Joanna Bieri,
So far you have not purchased dogs from our company!
The dogs are on sale starting 3-22-22.
Sincerely,
Management
--------------------

In [60]:
# You have to be careful
# This code has a weird result.
write_email('Joanna','Bieri',product='dogs',sale_date='3-22-22',number=7)

Dear Joanna Bieri,
As of False you have purchased 7 dogs from our company!
The dogs are on sale starting 3-22-22.
Sincerely,
Management

### Practice 4

Write your own code that constructs some sort of email. It should contain at least three required parameters and two optional or default parameters. 

Then use this function to write emails to a list (or dictionary) of people.

If you need inspiration you could look back at some of the examples from our past code where we wrote emails to invite people to parties, or to see a product.

In [65]:
# Your code here

def send_email(first,last,bring='balloons',age=0,number=0):
    '''Sends a email to first last about party
        something they will bring to the party, default is balloons'''
    
    if age:
        message = f'Dear {first.title()} {last.title()},'
        message += f"\nYou are invited to Jane's {age}th birthday party!\n"
        message += f'We are asking if you could provide the {bring}. We will need {number}.\n'
        message += f'Sincerely,\nYour best friend'
        print(message)
    else:
        message = f'Dear {first.title()} {last.title()},'
        message += f"\nYou are invited to Jane's birthday party!\n"
        message += f'We are asking if you could provide the {bring}. We will need {number}.\n'
        message += f'Sincerely,\nYour best friend'
        print(message)

In [66]:
send_email('Mazzie','Tetens',bring='bundt cakes',age=21,number=4)

Dear Mazzie Tetens,
You are invited to Jane's 21th birthday party!
We are asking if you could provide the bundt cakes. We will need 4.
Sincerely,
Your best friend

####

## Functions are Really Awesome!

Remeber in programming assignment 5 when we were looking at Starbucks Drinks and I asked you to find:

#### Which beverage category has:
- The most calories per drink?
- The most caffiene per drink?
- The most sugar per drink?
- The most proten per drink?

You probably wrote something like this:

In [25]:
# Import the data in the file
import pandas as pd
file_name = 'https://joannabieri.com/python/starbucks_drinkMenu_expanded.csv'
DF = pd.read_csv(file_name)

bev_cats = list(DF['Beverage_category'].unique())

most_cals = 0
most_caf = 0
most_sug = 0
most_pro = 0

for c in bev_cats:
    # c is a beverage category
    mask_cats = DF['Beverage_category']==c
    DF_cat = DF[mask_cats]
    total_drinks = len(DF_cat)
    
    total_cals = sum(DF_cat['Calories'])
    cal_per_drink = total_cals/total_drinks
    if cal_per_drink > most_cals:
        most_cals = cal_per_drink
        most_cal_category=c
        
    total_caf = sum(DF_cat['Caffeine (mg)'])
    caf_per_drink = total_caf/total_drinks
    if caf_per_drink > most_caf:
        most_caf = caf_per_drink
        most_caf_category=c
        
    total_sug = sum(DF_cat['Sugars (g)'])
    sug_per_drink = total_sug/total_drinks
    if sug_per_drink > most_sug:
        most_sug = sug_per_drink
        most_sug_category=c
        
    total_pro = sum(DF_cat['Protein (g) '])
    pro_per_drink = total_pro/total_drinks
    if pro_per_drink > most_pro:
        most_pro = pro_per_drink
        most_pro_category=c
        
print(f'{most_cal_category} have the most calories per drink at {most_cals}')
print(f'{most_caf_category} have the most mg caffeine per drink at {most_caf}')
print(f'{most_sug_category} have the most sugar per drink at {most_sug}')
print(f'{most_pro_category} have the most protein per drink at {most_pro}')

Smoothies have the most calories per drink at 282.22222222222223
Coffee have the most mg caffeine per drink at 293.75
Frappuccino® Blended Coffee have the most sugar per drink at 57.083333333333336
Smoothies have the most protein per drink at 17.11111111111111

#### This was probably really tedious to code up!

To write this code you had to copy and paste the main 5 lines of code over and over and CAREFULLY change the names. This probably had lots of typos and was a bit of a pain in the butt!

#### Here is the same code writen as a function:

In [26]:
# I try to import the data just once at the top
import pandas as pd
file_name = 'https://joannabieri.com/python/starbucks_drinkMenu_expanded.csv'
DF = pd.read_csv(file_name)

In [27]:
def get_most(col_name,DF):
    '''Function to calculate the drink category that has the most
       of the category in col_name'''
    bev_cats = list(DF['Beverage_category'].unique())
    most = 0
    for c in bev_cats:
        mask_cats = DF['Beverage_category']==c
        DF_cat = DF[mask_cats]
        total_drinks = len(DF_cat)

        total = sum(DF_cat[col_name])
        per_drink = total/total_drinks
        if per_drink > most:
            most = per_drink
            most_category=c
            
    print(f'{most_category} has the most {col_name} at {most} per drink.')

In [28]:
get_most('Calories',DF)

Smoothies has the most Calories at 282.22222222222223 per drink.

In [29]:
# But we could also loop through a bunch of them:
# What are the column names
column_names = [
 'Calories',
 'Trans Fat (g) ',
 'Saturated Fat (g)',
 'Sodium (mg)',
 'Total Carbohydrates (g) ',
 'Cholesterol (mg)',
 'Dietary Fibre (g)',
 'Sugars (g)',
 'Protein (g) ',
 'Caffeine (mg)']

for col in column_names:
    get_most(col,DF)

Smoothies has the most Calories at 282.22222222222223 per drink.
Signature Espresso Drinks has the most Trans Fat (g)  at 2.7125 per drink.
Signature Espresso Drinks has the most Saturated Fat (g) at 0.05 per drink.
Signature Espresso Drinks has the most Sodium (mg) at 9.625 per drink.
Frappuccino® Blended Coffee has the most Total Carbohydrates (g)  at 230.27777777777777 per drink.
Frappuccino® Blended Coffee has the most Cholesterol (mg) at 59.638888888888886 per drink.
Smoothies has the most Dietary Fibre (g) at 6.777777777777778 per drink.
Frappuccino® Blended Coffee has the most Sugars (g) at 57.083333333333336 per drink.
Smoothies has the most Protein (g)  at 17.11111111111111 per drink.
Coffee has the most Caffeine (mg) at 293.75 per drink.

In [30]:
# Be careful - Data is never perfect!
# If I try to get total fat I get an error
get_most('Total Fat (g)',DF)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [31]:
# For some reason the total fat was read in as a string!
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Beverage_category         242 non-null    object
 1   Beverage                  242 non-null    object
 2   Beverage_prep             242 non-null    object
 3   Calories                  242 non-null    int64
 4   Total Fat (g)             242 non-null    object
 5   Trans Fat (g)             242 non-null    float64
 6   Saturated Fat (g)         242 non-null    float64
 7   Sodium (mg)               242 non-null    int64
 8   Total Carbohydrates (g)   242 non-null    int64
 9   Cholesterol (mg)          242 non-null    int64
 10  Dietary Fibre (g)         242 non-null    int64
 11  Sugars (g)                242 non-null    int64
 12  Protein (g)               242 non-null    float64
 13  Vitamin A (% DV)          242 non-null    object
 14  Vitamin C (% DV)          242 non-null    object
 15  Calcium (% DV)            242 non-null    object
 16  Iron (% DV)               242 non-null    object
 17  Caffeine (mg)             241 non-null    float64
dtypes: float64(4), int64(6), object(8)
memory usage: 34.2+ KB

In [32]:
# We would have to fix this first!
# Lets look at what is wrong
for f in DF['Total Fat (g)']:
    try:
        float(f)
    except:
        print(f)

3 2

In [ ]:
for i, f in enumerate(DF['Total Fat (g)']):
    try:
        DF['Total Fat (g)'].iloc[i] = float(f)
    except:
        DF['Total Fat (g)'].iloc[i] = float(f.replace(' ','.'))

In [34]:
get_most('Total Fat (g)',DF)

Signature Espresso Drinks has the most Total Fat (g) at 5.275 per drink.

### Mini Challenge Problem:

There are also errors in the columns:

     'Vitamin A (% DV) ' 
     'Vitamin C (% DV)'
     'Calcium (% DV) '
     'Iron (% DV) '

These are read as strings because of the % sign. See if you can write a function that will fix this. Given a column name, go through an change all the percents to floats. Then get the data for which category has the most of each mineral or vitimin.

In [35]:
file_name = 'https://joannabieri.com/python/starbucks_drinkMenu_expanded.csv'
DF = pd.read_csv(file_name)
# Your code here

### Practice 5

Let's go back to the Disney data that we looke at during Lecture Practice Problems Day 12.

Write code that will display a data frame of the most money making (inflation adjusted gross) movies in a specific genre. Here are some specifications:

- given the parameter "genre" it will look up the top 'n' movies in that genere. 
- give n a default value of 5, but n should be a parameter that the user can change.
- the code should check that the given genre name exists in the dataframe and give a message if it doesn't
- the code should print out how many movies it found. For example if the user asked for the top 100 in a category that only has 10 movies, you would print we found 10.

You can copy and paste code that you wrote for Day 12 if it helps get you going. You are not expected to have all these commands memorized.

In [67]:
import pandas as pd
file_name = 'https://joannabieri.com/python/disney_movies.csv'
DF = pd.read_csv(file_name)
DF

,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,1937-12-21,Musical,G,184925485,5228953251
1,Pinocchio,1940-02-09,Adventure,G,84300000,2188229052
2,Fantasia,1940-11-13,Musical,G,83320000,2187090808
3,Song of the South,1946-11-12,Adventure,G,65000000,1078510579
4,Cinderella,1950-02-15,Drama,G,85000000,920608730
...,...,...,...,...,...,...
574,The Light Between Oceans,2016-09-02,Drama,PG-13,12545979,12545979
575,Queen of Katwe,2016-09-23,Drama,PG,8874389,8874389
576,Doctor Strange,2016-11-04,Adventure,PG-13,232532923,232532923
577,Moana,2016-11-23,Adventure,PG,246082029,246082029
578,Rogue One: A Star Wars Story,2016-12-16,Adventure,PG-13,529483936,529483936

In [73]:
# Your code here

def top_movies(genre,DF,n=5):
    genres = list(DF['genre'].unique())
    if genre in genres:
        mask = DF['genre']==genre
        DF_genre = DF[mask]
        DF_top = DF_genre.sort_values('inflation_adjusted_gross',ascending=False).iloc[:n]
        print(f'Displaying the top {len(DF_top)} movies:\n')
        display(DF_top)
        
    else:
        print(f'{genre} not found in our data. Check the spelling. We have the following genres:\n')
        for g in genres:
            print(g)

In [74]:
top_movies('Thriller/Suspense',DF,5)

Displaying the top 5 movies:

,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross
309,The Sixth Sense,1999-08-06,Thriller/Suspense,PG-13,293506292,485424724
367,Signs,2002-08-02,Thriller/Suspense,PG-13,227965690,330754439
116,The Hand That Rocks the Cradle,1992-01-10,Thriller/Suspense,R,88036683,178831137
406,The Village,2004-07-30,Thriller/Suspense,PG-13,114197520,155021748
336,Unbreakable,2000-11-22,Thriller/Suspense,PG-13,94999143,148208901

## Returning Values from a Function

Sometimes you need variables calculated from the function to use in later calculations. You can return values from the function!

Here is an example where instead of printing the email address we return the information.

In [75]:
def make_email(first,last):
    '''Creates an email address for first last'''
    my_email = f'{first.lower()}_{last.lower()}@redlands.edu'
    return my_email

In [76]:
email = make_email('Joanna','Bieri')

In [77]:
print(email)

joanna_bieri@redlands.edu

This allows us more advanced operations and the ability to combine functions and tie together operations.

In [78]:
def write_email(first,last):
    email_address = make_email(first,last)
    message = f'TO: {email_address}'
    message += f'\n\nThis is a spam email!'
    message += f'\nLove,\nYour friendly local spammer.'
    print(message)

In [79]:
write_email('Joanna','Bieri')

TO: joanna_bieri@redlands.edu

This is a spam email!
Love,
Your friendly local spammer.

### Practice 6

Define a function that returns the solution to the pathagorean formula:

$$ a^2 + b^2 = c^2 $$

It should have three optional parameters (a,b,c) and then depending on which two are given returns the solution for the third.

For example:

- import numpy as np
- a=2, b=3
- the code: if c is not specified then solve ans = np.sqrt(a^2+b^2)
- return the answer.

It should let the user send in any combo of two constants AND give an error if the user sends in less then two or more than two.

In [87]:
import numpy as np

def pythagorean(a=None, b=None, c=None):
    values_given = [a, b, c].count(None)

    if values_given != 1:
        print("Error: You must provide exactly two values.")
        return None

    if c is None:
        ans = np.sqrt(a**2 + b**2)
        return ans

    elif a is None:
        ans = np.sqrt(c**2 - b**2)
        return ans

    elif b is None:
        ans = np.sqrt(c**2 - a**2)
        return ans

In [84]:
DF_new = top_movies('Thriller/Suspense',DF,5)
plot_movies('Top Thriller Suspense Movies',DF_new

_IncompleteInputError: incomplete input (762271374.py, line 2)

### Challenge

Copy and paste the code you wrote above that gets the top n movies in a genre from the Disney data frame. We are going to update this code AND write a new function.

- Update your genre code to return the dataframe containing just to top n movies.
- Write a function that takes as an input a plot title, and a dataframe and then plots the movie titles vs the inflation adjusted gross  on a barplot. It should show a plot of the data.

- After both of these work independently, see if you can update the plotting function so that it automatically calls the genre function. In other words, you would add an inputs that are the genre and number of movies, and then call the first function from within the second.

In [ ]:
# Your code here

In [ ]:
# Your challenge code here

# Some Important Ideas:

1. The parameters defined in the function can be named anything and they are only used within that function.
2. Global parameters are known by the function (eg. technically we did not have to pass the DF to the functions above - but it's good to get in the practice of sending all needed data in).
3. You can send in and return just about anything: Lists, Dictionaries, Data Frames, Strings, Tuples, etc...
4. You should be a bit careful about what data your functions are writing over (eg. If you send a list into a function you should do calculations on a copy of a slice. This will stop your functions from altering the origial list.

         my_new_list = my_list[:]